### ISSUE TITLE
Prebuilt analyzer image?

### ISSUE THREAD

**Issue by Inrego** [mmcc-xx/BirdCAGE#10]
Any chance you'd build the docker image and upload to docker hub or similar? That way, possible future changes to it would also be easier to deploy, as people can just update their container (Watchtower or other similar tools will even auto update it, or notify of an update).

**Comment by mmcc-xx** [comment]
Yeah I'm thinking I should do that, at least until the BirdNET-Analyer decides to post an official image. Thanks for the suggestion... stand by.

**Comment by mmcc-xx** [comment]
image has been added.
