### ISSUE TITLE
Password header is missing

### ISSUE THREAD

**Issue by brucewinter** [mmcc-xx/BirdCAGE#12]
Cool project, excited to get it running!

I got this error when trying to add a stream:

curl -X 'POST'  'http://192.168.86.151:7007/api/streams' -H 'accept: application/json'  -H 'Content-Type: application/json' -d '{  "name": "c7",  "password": "birdcage",  "address": "rtsp://192.168.86.152:8554/c7_sub",  "protocol": "rtsp",  "transport": "TCP"}'

{"error":"Password header is missing"}

It wasn't clear where to enter the password?

**Comment by mmcc-xx** [comment]
You should see the following at http://frontendaddress/streamsettings. If you don't , please grab a screenshot.

The UI is bad. I'm intending to add actual persisted authentication.

![image](https://github.com/mmcc-xx/BirdCAGE/assets/1315341/483822cf-f91a-4a21-a7b5-492db0ef8e51)

**Comment by mmcc-xx** [comment]
Sounds good!
