### ISSUE TITLE
Apprise MQTT record is missing sound file

### ISSUE THREAD

**Issue by brucewinter** [mmcc-xx/BirdCAGE#21]
Thanks for adding the new Apprise notification option!    Is partly working for me:

 - gmail record works!  I get an email with name, score, stream name, time, and an attachment with the mp3 file
 - gmail log and alert options do not seem to do anything.  Not sure what these are for, seems the record data has all I need
 - mqtt record partly works.  I get the same data I got in gmail, except it is missing the mp3 data.

The new Title option works also.   Thanks for all your efforts!

**Comment by mmcc-xx** [comment]
Hi Bruce - Any given detection is assigned an ignore, log, record or alert "action" based on where the bird species is on the likelihood scale and your filter settings. For the purposes of notifications, the log, record, and alert levels are just used as ways to differentiate levels of importance. So maybe you have log, record and alert level detections all sent to mqtt, you have record and alert also sent to gmail, and you have alert level also sent to SMS. Or you could have just log level sent to mqtt, just record level sent to gmail, and just alert level sent to SMS. It's up to your configuration.

I also noticed that MQTT doesn't include the "attachment" . I assume that is a function of how Apprise. I'm planning to put in native MQTT support with JSON payloads soon... like in the next couple of days.

**Comment by brucewinter** [comment]
My bad, I had not played with the filters yet so did not understand log/record/alert.  Makes sense now, thanks!
