### ISSUE TITLE
Default user/pass not working

### ISSUE THREAD

**Issue by tcatkins99** [mmcc-xx/BirdCAGE#31]
Hello, I just spun up this container following the docs in the wiki but when I go the preferences page to login, I use `admin` and `password` per https://github.com/mmcc-xx/BirdCAGE/wiki/Preferences but i'm getting a 401 error. Did these values change or is there a typo somewhere? Looking forward to giving this app a spin!

**Comment by mmcc-xx** [comment]
I apologize- the default password is birdcage

**Comment by mmcc-xx** [comment]
I fixed it.

You might also want to pull the image again. I just backed out a change that screwed things up quite a bit.

**Comment by tcatkins99** [comment]
Coo, that did it!
