### ISSUE TITLE
wrong version - docker-compose

### ISSUE THREAD

**Issue by GHSTUDIO1** [mmcc-xx/BirdCAGE#34]
Following your installation guide, I copy the file into docker-compose.yml but when I try to do the docker-compose, I get a message about a string error in the version.  I removed some strange characters and left Version "3.8"....but then I get Version is unsupported.  I just installed docker and docker-compose so there's some mismatch going on here.

**Comment by GHSTUDIO1** [comment]
changed to version 2.1  (note: I used debian which is likely on an older version of Docker)...and the install started.  Then I got:

Creating birdcage_redis_1         ... error

ERROR: for birdcage_redis_1  Cannot start service redis: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: proc

I'm going to try it with an Ubuntu lxc from scratch.....

**Comment by GHSTUDIO1** [comment]
update:  installed Ubutnu in LXC. Had to install docker,docker-compose.....copied docker-compose.yml changing 75 to my IP and tried docker-compose.  Failed again on version.  Changed Version to 2.1 and it installed cleanly.

Those mystery bytes must have been user error....forget them.

Now I have to figure out how to make this useful :)

**Comment by mmcc-xx** [comment]
> Now I have to figure out how to make this useful :)

Usefulness is overrated
