### ISSUE TITLE
How do you configure USB microphone for docker setup?

### ISSUE THREAD

**Issue by deepcoder** [mmcc-xx/BirdCAGE#36]
First, thank for your work on this project.

I do not see any instructions for how to connect a USB microphone your system. Can you explain how to do this?

Thx!

**Comment by mmcc-xx** [comment]
Well, you don’t. Right now it only works with network audio streams. However there might be a way to take sound device input and serve it with rtsp ffmpeg.

**Comment by brucewinter** [comment]
After many attempts, I managed to get vlc into sending a audio only stream that birdCAGE can use via the http protocol.  

On windows: 
  vlc dshow:// :dshow-vdev=none :dshow-adev="Microphone (Logitech BRIO)" :live-caching=100 :sout="#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{dst=:8081/birdcage.mp3}" :sout-all :sout-keep

On linux (tested on Ubuntu on a nuc and a raspberry pi): 
  cvlc  alsa://plughw:1,0  :live-caching=100 :sout="#transcode{vcodec=none,acodec=mp3,ab=128,channels=2,samplerate=44100,scodec=none}:http{dst=:8081/birdcage.mp3}" :sout-all :sout-keep

To find the name of your microphone, run vlc with out any arguments to get the gui, then:  media -> stream -> capture device -> audio device name.

**Comment by deepcoder** [comment]
The whole VLC thing seems pretty kludgy, however I will try your suggestions. Thanks for your direction. Sorry, but I am not going to add Windows into this equation. Did not some folks over at BirdNET-Pi have a container version of that code running with USB microphone? Maybe going back to that code and refactoring might be a better start for me.

This whole workflow seems way too complicated. You have four docker containers, that seems pretty weighty. Does anyone document their code anymore, what a curmudgeon I am...but why is there code to interface to YouTube in this???? I'm thinking this code has some serious 'technical debt'.

**Comment by deepcoder** [comment]
🎤 💧

**Comment by mmcc-xx** [comment]
> Did not some folks over at BirdNET-Pi have a container version of that code running with USB microphone? Maybe going back to that code and refactoring might be a better start for me.

There are folks that have it running in VMs. I started there and was not happy with the performance. I then dug into the code with an eye towards containerizing. It did not look promising so I started over from scratch.

> You have four docker containers, that seems pretty weighty. 

Well, there are 3. 

One runs the analysis service and is slightly modified from what BirdNET-Analyzer provides. I hope one day that I'll be able to switch to using an image they manage and provide a well defined interface for. That will make it easier for users to upgrade as new models come along, and maybe use older versions if the older versions meet their needs better.

One runs the back end application. This does the audio capture, calls the analysis service, store results, provides an API, pushes MQTT publications and notifications.

One runs the front end application. This consumes the API provided by the back end application and provides the user interface.

To me this seems like a very logical segmentation of functionality. I would someday like to shed responsibility for maintaining the analysis capabilities, hence it is split into its own container. By splitting the back end from the front end it allows the possibility of executing them on separate platforms. Perhaps someone might want to run the front end in the cloud and the back end at a remote site. Perhaps someone might want to come up with a front end that interfaces with multiple backends... these are entirely possible. Plus it makes maintenance of the two easier when there is a wall of an API between them.

Plus containers are very light weight for what they provide - they put the micro in micro service. I have a refurbished business desktop PC that I bought several years ago sitting in my basement running this app and a bunch of others... I just checked and I think it is running 50 containers. It has a 4th gen i5 processor that was launched in 2014.

Plus plus this app is not designed around optimization for SBCs. I would love for it to be able to run on them, but primarily I want to be able to take advantage of the capabilities of more capable hardware.

> ... why is there code to interface to YouTube in this???? I'm thinking this code has some serious 'technical debt'.

I will not deny incurring technical debt, but this is not an example. I wanted to be able to set up a demo. The easiest way to set up a demo with a reliable source of audio that is going to have lots of bird songs was to pull in a YouTube live stream. Plus it gives new users a way to test out an installation. Here is the sum total of the code required to support YouTube in the back end application:

One lil routine to get the stream URL assoicated with the youtube livestream URL:
```
def get_youtube_stream_url(youtube_video_url, format_code=None):
    youtube_dl_command = ["youtube-dl", "-g"]

    if format_code:
        youtube_dl_command.extend(["-f", str(format_code)])

    youtube_dl_command.append(youtube_video_url)

    try:
        stream_url = subprocess.check_output(youtube_dl_command).decode("utf-8").strip()
        return stream_url
    except subprocess.CalledProcessError as e:
        print(f"Failed to get YouTube stream URL: {e}", flush=True)
        return None
```

And one lil if statement:
```
        elif protocol == 'youtube':
            youtube_stream_url = get_youtube_stream_url(stream_url, format_code=91)
            if youtube_stream_url is None:
                return {'status': 'failure', 'error': 'error getting youtube url'}
            (
                ffmpeg
                    .input(youtube_stream_url)
                    .output(output_filename, format='wav', t=seconds, loglevel='warning')
                    .run()
            )
```
That's it: well segmented from all of the other functionality, exceptions are handled, using existing popular libraries to do the real work. Not tech debt, and running 24x7 here: https://demo.birdcage.rocks/

Pull requests are gratefully accepted. I would love to see soundcard input work but I haven't gotten around to it yet, due in part to the fact that my machine is in my basement where there are very few birds. I think it would need...
* a modification to the docker-compose file to get a sound device mapped into the backed application
* a type of stream "protocol" and corresponding UI to allow the user to choose sound card input
* a way to handle that new stream protocol in the record_stream_ffmpeg routine in stream_processing.py

**Comment by mmcc-xx** [comment]
https://github.com/mmcc-xx/BirdCAGE/wiki/PulseAudio

**Comment by mmcc-xx** [comment]
@brucewinter just making sure you got a notification about this:
https://github.com/mmcc-xx/BirdCAGE/wiki/PulseAudio
Your VLC bridge is very impressive, but I hope you don't need it any more. Assuming, that is, pulseaudio works on Raspberry Pis. If it doesn't let me know and I'll look into mapping in an ALSA device.

**Comment by brucewinter** [comment]
Just read you PulseAudio wiki entry.  As you noted, looks a little tricky, but you is documented and I'm impressed at how quickly you added that!  

I may give it a go this weekend, but to be honest, I'm pretty happy with the vlc hack.  Once I got the magic incantation figured out, it is pretty simple to launch and has an added advantage that I can easily test the audio stream with another vlc session, although I probably could do that with you pulseaudio server also. 

Will let you know if/when I try out the PulseAudio option, thanks for adding that.
