### ISSUE TITLE
Localization not working on 2.4

### ISSUE THREAD

**Issue by ministryofsillywalks** [mmcc-xx/BirdCAGE#37]
I was using german locale on 2.3.
I updated to 2.4 and now the names are back to english.
I changed the locale to en and back to de in preferences but it stays english.
Any ideas?

**Comment by mmcc-xx** [comment]
I'll take a look. I assume if you move back to 2.3 localization works again?

**Comment by ministryofsillywalks** [comment]
Can confirm its working again on 2.3

**Comment by Inrego** [comment]
I am having the same problem

**Comment by mmcc-xx** [comment]
Should now be fixed - do a `docker pull mmcc73/birdnetserver2.4:latest` to get the latest. I had neglected to copy the localized labels into the image when I updated the model.

arm64 version will be available in a couple hours.
