### ISSUE TITLE
Ability to disable CORS

### ISSUE THREAD

**Issue by NickM-27** [mmcc-xx/BirdCAGE#48]
I am running on Unraid so docker compose is not an option for me. I have the separate containers running but of course the frontend and backend share different ports which means the CORS is going to fail. I'd like to be able to disable it or some way to accept cross origin requests. I tried setting the variable to `*` but it did not work.

**Comment by matthew73210** [comment]
Hello, are you 100% sure that you can't get docker-compose on unraid? I have no experience with unraid but I've deffo heard it's poss with something like a plug-in. Apologies if you've already tried this.

**Comment by NickM-27** [comment]
Last time I tried it was not possible, but it does seem that there is now a plugin in the community store which has worked so thanks for the suggestion.
