### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by matthew73210** [mmcc-xx/BirdCAGE#53]
Hey,

In the frontend container, I was having a go at building it local to do some work and it's missing the requirements.txt and thus won't build. Is is the same as the backend ?

Cheers

**Comment by kchristensen** [comment]
It’s different, but you can steal it out of my pr over here: https://github.com/mmcc-xx/BirdCAGE/pull/43

**Comment by matthew73210** [comment]
Safe

Cheers, did try it with the backend one and it started. Tad slow though but could be on my end.
