### ISSUE TITLE
Default credentials return an error

### ISSUE THREAD

**Issue by matt-wirth** [mmcc-xx/BirdCAGE#60]
just installed latest everything in docker. On first login I attempt to go to preferences and get a login prompt. When I click on the "Login" button, I get "An error occurred while logging in"

Thanks!

**Comment by mmcc-xx** [comment]
Hmm... when you log in (as well as when you do most other things), some client side script tries to call the API server. So, lets first make sure you can get to the API server from your browser. 

In your docker-compose file you'll have defined an environment variable like so:
 API_SERVER_URL: http://192.168.1.75:7007

Try to go to that URL from your browser and make sure you see a UI that looks like the screenshot below. We'll then go from there.

![image](https://github.com/mmcc-xx/BirdCAGE/assets/1315341/a6080d8f-8246-4a02-9551-b9817d970abd)

**Comment by matt-wirth** [comment]
Yep, I get the swagger docs. 

![Screenshot_20230723_172120_Firefox](https://github.com/mmcc-xx/BirdCAGE/assets/39602587/b2c8b657-1767-411f-bf63-7503117e8d70)

From the docker container: 
```root@17555cc0acba:/# curl http://birdcage_back:7007
<!doctype html>
<html lang=en>
<title>Redirecting...</title>
<h1>Redirecting...</h1>
<p>You should be redirected automatically to the target URL: <a href="/api/docs">/api/docs</a>. If not, click the link.
root@17555cc0acba:/#```

**Comment by mmcc-xx** [comment]
"An error occurred while logging in" is the message shown when an exception occurs when trying to call the login API. Would you mind sharing your docker-compose file? Maybe the CORS_ORIGINS variable isn't set up right?

In the browser, after you get that error, you can try hitting F12 to see if you can get any information on the error. I'm not sure if anything will be listed because the exception is being handled.

**Comment by matt-wirth** [comment]
Okay, I'll do some more investigation and get back to you.

**Comment by matt-wirth** [comment]
@mmcc-xx yep, user error. Had my addressing wrong in the env variables. Thank you for pointing me in the right direction, and for this super fun app!

**Comment by mmcc-xx** [comment]
Cool - glad you got it figured out!
