### ISSUE TITLE
Preferences Information

### ISSUE THREAD

**Issue by mochman** [mmcc-xx/BirdCAGE#7]
Can you explain what all the preferences do?  I understand Lat/Long & Confidence, but what about the other ones?  Thanks.

**Comment by mmcc-xx** [comment]
Sure - I should probably put this info on the page
**Recording Length** - how long the clips are that get sent to the analysis service. By default, the streams are recorded in 15 second increments.
**Confidence** - The minimum confidence score from the analysis service to be considered a positive detection. If you make the number lower, you'll get fewer false negatives but more false positives
**Extraction Length** - the analysis service looks at 3 second chunks of the recordings that are sent to it. When there's a positive detection, I'll try to get Extraction Length amount of audio with out of the recording with the detection in the middle. If the detection is in the first or last interval of the recording then that won't be possible
**Overlap** - I pass this value on to the analysis service. Their documentation says "Overlap of prediction segments. Values in [0.0, 2.9]". I think what this means is that if you set it to 1.5, it will analyze seconds 0-3, then 1.5-4.5, then 3-6, then 4.5-7.5, etc., therefore overlapping the chunks by 1.5 seconds
**Sensitivity** - again I pass this through. "'Detection sensitivity; Higher values result in higher sensitivity. Values in [0.5, 1.5]. " I haven't messed with it, so I'm not sure of the effect.
**SF Threshold** - "Minimum species occurrence frequency threshold for location filter. Values in [0.01, 0.99]" . If you set this to lower values, it will match on more rare species for your location and time of year. If you set it to higher values, rarer species will be ignored.

**Comment by mochman** [comment]
Thanks!
