### ISSUE TITLE
Daylight Savings time

### ISSUE THREAD

**Issue by tismepaulo** [mmcc-xx/BirdCAGE#9]
I can't see any way to change the time or a setting for timezone to compensate for daylight savings time. My recordings are an hour out. Is it possible to add this?

**Comment by mmcc-xx** [comment]
In the docker-compose file in the repo, the time and timezone are passed in from the host machine. 

Does your docker-compose file have those volumes? Is the time on the host machine correct?

**Comment by tismepaulo** [comment]
Oops, apologies. I'll look into the time on the host machine.
